# Generated by Django 3.2.8 on 2021-10-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(max_length=30)),
                ('measurement', models.DecimalField(decimal_places=1, max_digits=6)),
                ('date', models.DateField()),
            ],
        ),
    ]
