# Generated by Django 3.2.8 on 2021-10-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='measurement',
            field=models.IntegerField(),
        ),
    ]
