# Generated by Django 3.2.8 on 2021-10-15 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('body_part', models.CharField(max_length=50)),
                ('equipment', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('notes', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workout_folders.workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_description', models.CharField(blank=True, max_length=200)),
                ('folder_name', models.CharField(default='Workouts', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('exercise', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.PROTECT, to='workout_folders.exercise', to_field='name')),
                ('workout', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workout_folders.workout')),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_folders.workoutfolder'),
        ),
    ]
