# Generated by Django 3.2.8 on 2021-10-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_folders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouthistory',
            name='workout_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
