# Generated by Django 3.2.8 on 2021-10-09 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_folders', '0002_alter_workoutexercises_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercises',
            name='exercise',
            field=models.ForeignKey(default='standing', on_delete=django.db.models.deletion.CASCADE, to='workout_folders.exercise'),
        ),
        migrations.AlterField(
            model_name='workoutexercises',
            name='workout',
            field=models.ForeignKey(default='my workout', on_delete=django.db.models.deletion.CASCADE, to='workout_folders.workout'),
        ),
    ]
