# Generated by Django 3.2.8 on 2021-10-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_folders', '0004_auto_20211009_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
