# Generated by Django 3.2.8 on 2021-10-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasts',
            name='user',
            field=models.IntegerField(),
        ),
    ]
