# Generated by Django 3.2.8 on 2021-10-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasts', '0003_auto_20211021_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasts',
            name='end',
            field=models.DateTimeField(),
        ),
    ]
